# -*- coding: utf-8 -*-
"""exoplanet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvd5I533jMdMAFhCWYuOcIXpbhV03UZd
"""

# IMPORTS

import argparse
from pathlib import Path
from urllib.parse import quote
import joblib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report,
)
from sklearn.utils.class_weight import compute_class_weight

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping

# ============================================================
# IMPORTS
# ============================================================

import os
import argparse
import requests
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import numpy as np

from pathlib import Path
from urllib.parse import quote

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42
np.random.seed(SEED)

FEATURE_COLUMNS = [
    "koi_period",
    "koi_impact",
    "koi_duration",
    "koi_depth",
    "koi_prad",
    "koi_teq",
    "koi_insol",
    "koi_model_snr",
    "koi_steff",
    "koi_slogg",
    "koi_srad",
]

TARGET_COLUMN = "koi_disposition"

MODEL_DIR = "models"
Path(MODEL_DIR).mkdir(parents=True, exist_ok=True)

MODEL_PATH = os.path.join(MODEL_DIR, "exoplanet_model_fixed.h5")
WEIGHTS_PATH = os.path.join(MODEL_DIR, "exoplanet_model_fixed.weights.h5")
SCALER_PATH = os.path.join(MODEL_DIR, "scaler.pkl")
ENCODER_PATH = os.path.join(MODEL_DIR, "label_encoder.pkl")


# ============================================================
# DATA DOWNLOAD
# ============================================================

def download_koi_data(output_path="data/koi_exoplanet_data.csv"):
    Path("data").mkdir(parents=True, exist_ok=True)

    query = f"""
    SELECT {', '.join([TARGET_COLUMN] + FEATURE_COLUMNS)}
    FROM cumulative
    WHERE koi_disposition IS NOT NULL
    """

    url = (
        "https://exoplanetarchive.ipac.caltech.edu/TAP/sync"
        f"?query={quote(query)}&format=csv"
    )

    print("Downloading dataset...")

    r = requests.get(url, timeout=60)
    if r.status_code != 200:
        raise RuntimeError("Download failed")

    Path(output_path).write_text(r.text, encoding="utf-8")
    df = pd.read_csv(output_path)

    if df.empty:
        raise ValueError("Empty dataset")

    return df


# ============================================================
# PREPROCESSING
# ============================================================

def preprocess(df):
    df = df[[TARGET_COLUMN] + FEATURE_COLUMNS].dropna()

    X = df[FEATURE_COLUMNS].values
    y = df[TARGET_COLUMN].values

    encoder = LabelEncoder()
    y = encoder.fit_transform(y)

    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    return X, y, scaler, encoder


# ============================================================
# MODEL
# ============================================================

def build_model(input_dim, num_classes):
    model = Sequential([
        Dense(256, activation="relu", input_shape=(input_dim,)),
        Dropout(0.35),

        Dense(128, activation="relu"),
        Dropout(0.30),

        Dense(64, activation="relu"),
        Dropout(0.20),

        Dense(num_classes, activation="softmax"),
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model


# ============================================================
# PIPELINE
# ============================================================

def run():
    df = download_koi_data()
    X, y, scaler, encoder = preprocess(df)

    joblib.dump(scaler, SCALER_PATH)
    joblib.dump(encoder, ENCODER_PATH)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=SEED, stratify=y
    )

    class_weights = compute_class_weight(
        class_weight="balanced",
        classes=np.unique(y_train),
        y=y_train
    )

    class_weight_dict = {
        cls: w for cls, w in zip(np.unique(y_train), class_weights)
    }

    model = build_model(X_train.shape[1], len(np.unique(y)))

    early_stop = EarlyStopping(
        monitor="val_loss",
        patience=10,
        restore_best_weights=True
    )

    history = model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=100,
        batch_size=32,
        callbacks=[early_stop],
        class_weight=class_weight_dict
    )

    preds = np.argmax(model.predict(X_test), axis=1)

    print("\nAccuracy:", accuracy_score(y_test, preds))
    print(classification_report(y_test, preds))

    model.save(MODEL_PATH)
    model.save_weights(WEIGHTS_PATH)

    print("\nSaved model + scaler + encoder in /models")


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    run()

!pip install streamlit

!ls

!streamlit run app.py & npx localtunnel --port 8501

!ps -ef | grep streamlit